# Generated by Django 4.2.28 on 2026-03-18 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lead_enrollment.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("database_name", models.CharField(max_length=200)),
                ("admin_email", models.CharField(max_length=200)),
                ("status", models.CharField(default="active", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomAdmissionField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tab_name", models.CharField(max_length=50)),
                ("field_name", models.CharField(max_length=100)),
                ("field_label", models.CharField(max_length=100)),
                ("field_type", models.CharField(max_length=50)),
                (
                    "placeholder",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("required", models.BooleanField(default=False)),
                ("options", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "custom_admission_fields",
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("phone", models.CharField(max_length=10)),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("education", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "work_experience",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("next_follow_up_date", models.DateField(blank=True, null=True)),
                ("course_interested", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Contacted", "Contacted"),
                            ("Qualified", "Qualified"),
                            ("Lost", "Lost"),
                            ("Dead", "Dead"),
                            ("Converted", "Converted"),
                            ("Follow-up", "Follow-up"),
                        ],
                        default="New",
                        max_length=50,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("company_id", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("ip_address", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("company_id", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(max_length=10)),
                ("dob", models.DateField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("blood_group", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "guardian1_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "guardian1_occupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "guardian1_relation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "guardian1_phone",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "guardian2_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "guardian2_occupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "guardian2_relation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "guardian2_phone",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "college_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "year_of_passing",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("marks", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "work_experience",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "years_of_experience",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("profession", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("skills", models.TextField(blank=True, null=True)),
                (
                    "student_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=lead_enrollment.models.student_file_upload_path,
                        validators=[lead_enrollment.models.validate_file_size],
                    ),
                ),
                (
                    "id_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=lead_enrollment.models.student_file_upload_path,
                        validators=[lead_enrollment.models.validate_file_size],
                    ),
                ),
                (
                    "id_proof_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("courses", models.JSONField(blank=True, default=list, null=True)),
                (
                    "total_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "final_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fee_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Partially Paid", "Partially Paid"),
                            ("Fully Paid", "Fully Paid"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "certificate_status",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("Needs to Apply", "Needs to Apply"),
                        ],
                        default="Needs to Apply",
                        max_length=20,
                    ),
                ),
                ("certificate_applied", models.BooleanField(default=False)),
                (
                    "payment_scheme",
                    models.CharField(
                        choices=[
                            ("One-time", "One-time"),
                            ("Installment", "Installment"),
                        ],
                        default="One-time",
                        max_length=20,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("GPAY", "GPay"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("installments", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "batch",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL", "Full"),
                            ("FN", "FN"),
                            ("AN", "AN"),
                            ("ONLINE", "ONLINE"),
                        ],
                        default="FULL",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Suspended", "Suspended"),
                            ("Graduated", "Graduated"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("admission_date", models.DateField(auto_now_add=True, null=True)),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lead_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("company_id", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="WalkIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_by", models.CharField(max_length=100)),
                ("company_id", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walk_ins",
                        to="lead_enrollment.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPERADMIN", "Super Admin"),
                            ("ADMIN", "Admin"),
                            ("BDE", "BDE"),
                            ("CRO", "CRO"),
                            ("CRE", "CRE"),
                        ],
                        default="BDE",
                        max_length=20,
                    ),
                ),
                ("company_id", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentCustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lead_enrollment.customadmissionfield",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_values",
                        to="lead_enrollment.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_custom_field_values",
            },
        ),
        migrations.CreateModel(
            name="StudentChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("changed_by", models.CharField(max_length=50)),
                ("company_id", models.IntegerField(default=0)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="lead_enrollment.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_change_log",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=20)),
                ("status", models.CharField(default="Active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "staff_users",
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("amount_paid", models.IntegerField()),
                ("payment_mode", models.CharField(max_length=50)),
                ("company_id", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="lead_enrollment.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeadRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remark_text", models.TextField()),
                ("company_id", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remarks_history",
                        to="lead_enrollment.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("total_fee", models.IntegerField()),
                ("discount", models.IntegerField(default=0)),
                ("final_fee", models.IntegerField()),
                ("company_id", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="lead_enrollment.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("company_id", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
